<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <Deterministic>true</Deterministic>
    <VersionPrefix>0.4.2</VersionPrefix>
    <Authors>YAMium</Authors>
    <Company>YAMium</Company>
    <Copyright>Copyright (C) 2026 YAMium</Copyright>
    <PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/YAMium/FaLoudit</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
</Project>
