<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FalloutLoc.Backends</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Mutagen.Bethesda.Fallout3" Version="[0.54.4]" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../FalloutLoc.Core/FalloutLoc.Core.csproj" />
  </ItemGroup>
</Project>
